# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-21 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docstore', '0002_auto_20180421_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
