# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-21 03:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docstore', '0003_auto_20180421_0823'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Artifact',
        ),
    ]
