# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-21 06:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('docstore', '0005_auto_20180421_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='artifact_file',
            field=models.FileField(default=datetime.datetime(2018, 4, 21, 6, 53, 8, 375592, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
